// Rose/Stone Dimension Design System
// All 104 deployed websites organized by project group with recommendations

export type Recommendation = "Keep" | "Delete" | "Combine";
export type PolishLevel = "Polished" | "Draft/WIP" | "Blank/Error";

export interface Site {
  id: number;
  name: string;
  url: string;
  dateDeployed: string;
  status: "Public" | "Published" | "Private";
  polishLevel: PolishLevel;
  recommendation: Recommendation;
  purpose: string;
  group: string;
}

export interface SiteGroup {
  id: string;
  name: string;
  description: string;
  sites: Site[];
}

export const siteGroups: SiteGroup[] = [
  // ─── SUMMER CAMP ENROLLMENT ───────────────────────────────────────────────
  {
    id: "summer-camp",
    name: "Summer Camp Enrollment",
    description: "Comprehensive resource hub for summer camp enrollment training, guides, and communication tools.",
    sites: [
      {
        id: 1,
        name: "Summer Camp Enrollment Resources",
        url: "https://yfnbtxup.manus.space",
        dateDeployed: "May 18, 2025",
        status: "Published",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "This is the most recent and fully published version of your Summer Camp Enrollment hub. It includes interactive enrollment guides, staff training modules, communication tools, and manager resources all in one place. This is the one to keep as your primary reference.",
        group: "summer-camp",
      },
      {
        id: 2,
        name: "Website - qqczrspc",
        url: "https://qqczrspc.manus.space",
        dateDeployed: "May 18, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "This is an identical duplicate of the Summer Camp Enrollment Resources hub above, deployed on the same day. It has the exact same content, structure, and sections. Safe to delete since the primary version (yfnbtxup) is the one to keep.",
        group: "summer-camp",
      },
      {
        id: 3,
        name: "Summer Camp Enrollment Resources",
        url: "https://bvpxezze.manus.space",
        dateDeployed: "May 17, 2025",
        status: "Published",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "This is an older version of the Summer Camp Enrollment hub, deployed one day before the final version. The content is essentially the same as the May 18 version. Since the newer version supersedes it, this one can be safely deleted.",
        group: "summer-camp",
      },
    ],
  },

  // ─── GYMNASTICS SALES TRAINING ────────────────────────────────────────────
  {
    id: "sales-training",
    name: "Gymnastics Sales Training",
    description: "The Belief + Knowledge Sales System for Gymnastics — Windows & Doors conversation technique training.",
    sites: [
      {
        id: 4,
        name: "Sales Specialist Program Documentation",
        url: "https://salesdocs-5vzxrauk.manus.space",
        dateDeployed: "Dec 5, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "This is the most comprehensive and up-to-date version of your gymnastics sales training system. It includes a full 4-week pilot program, detailed job descriptions, phone scripts, objection-handling exercises, and a metrics dashboard. This is the definitive version to keep as your primary sales training resource.",
        group: "sales-training",
      },
      {
        id: 5,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://uacswweo.manus.space",
        dateDeployed: "Jun 17, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A polished mid-year version of the sales training site covering the Windows & Doors conversation technique, objection handling, and belief-building exercises. It was a solid version at the time but has since been superseded by the December update. Safe to delete.",
        group: "sales-training",
      },
      {
        id: 6,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://edezylyo.manus.space",
        dateDeployed: "Jun 17, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An exact duplicate of the Jun 17 sales training site above — same content, same structure, deployed on the same day. There is no reason to keep both. Delete this one.",
        group: "sales-training",
      },
      {
        id: 7,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://zeqhkuyo.manus.space",
        dateDeployed: "Jun 11, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An earlier June version of the sales system that added a Jayme's Login feature but otherwise contains the same core content. It was an intermediate build during development. Superseded by the Jun 17 and Dec 5 versions.",
        group: "sales-training",
      },
      {
        id: 8,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://hgifxcdo.manus.space",
        dateDeployed: "Jun 11, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A duplicate of the Jun 11 sales training site with identical content and layout. It was likely deployed as a test or backup during that development session. Safe to delete.",
        group: "sales-training",
      },
      {
        id: 9,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://vvoriwlm.manus.space",
        dateDeployed: "Jun 7, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An early June version focused on the introduction and belief-building exercises of the sales system. This was one of the first polished iterations of the training content. It has been fully superseded by later versions.",
        group: "sales-training",
      },
      {
        id: 10,
        name: "Website - hwfdxjju",
        url: "https://hwfdxjju.manus.space",
        dateDeployed: "Jun 7, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An unnamed version of the sales system deployed on Jun 7, covering the Windows & Doors analogy and core training sections. The generic name suggests it was a working draft that was never properly titled. Superseded.",
        group: "sales-training",
      },
      {
        id: 11,
        name: "https://nvewbqrm.manus.space",
        url: "https://nvewbqrm.manus.space",
        dateDeployed: "Jun 7, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Another unnamed Jun 7 version of the sales system with full content including the 70/30 Rule and YES-AND objection handling technique. It was part of the same development sprint as the other Jun 7 versions. Safe to delete.",
        group: "sales-training",
      },
      {
        id: 12,
        name: "https://issmtfmr.manus.space",
        url: "https://issmtfmr.manus.space",
        dateDeployed: "Jun 7, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Yet another unnamed Jun 7 version of the Belief + Knowledge Sales System with duplicate content. This appears to be one of several test deployments from the same session. Safe to delete.",
        group: "sales-training",
      },
      {
        id: 13,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://ehtoxofz.manus.space",
        dateDeployed: "Jun 6, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A comprehensive early version of the sales system from Jun 6, featuring the full Windows & Doors system, 70/30 Rule, and objection handling. This was one of the first complete builds of the training content. Superseded by all later versions.",
        group: "sales-training",
      },
      {
        id: 14,
        name: "Create Next App",
        url: "https://gymnasticssalestraining.manus.space",
        dateDeployed: "Apr 16, 2025",
        status: "Published",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "The very first version of the gymnastics sales training system, still named 'Create Next App' — a leftover from the initial project scaffolding. Despite being published, this is the oldest and most outdated version. Safe to delete.",
        group: "sales-training",
      },
      {
        id: 15,
        name: "ppjuivac.manus.space",
        url: "https://ppjuivac.manus.space",
        dateDeployed: "Apr 16, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An unnamed early version of the sales training system from the same April development session. It has the same content as the Apr 16 'Create Next App' version. Both are the oldest builds and have been fully superseded.",
        group: "sales-training",
      },
    ],
  },

  // ─── GYMNASTICS CONTENT HUB / CMS ────────────────────────────────────────
  {
    id: "content-hub",
    name: "Gymnastics Content Hub / CMS",
    description: "Content management systems, social media content databases, document hubs, and marketing catalogs for gymnastics.",
    sites: [
      {
        id: 16,
        name: "Ultimate Design Studio - Gymnastics Email Powerhouse",
        url: "https://ultdesign-pgp98n.manus.space",
        dateDeployed: "Sep 15, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A unique email design and generation platform that lets you select from FAQ, Quiz, and Complete email templates, then generate customized emails for specific gyms. It also includes AI-powered email analysis. This is a distinct tool from the other content managers and worth keeping.",
        group: "content-hub",
      },
      {
        id: 17,
        name: "Gym Content Manager",
        url: "https://kkgpsidz.manus.space",
        dateDeployed: "Aug 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A content management system for tracking monthly content assignments across gyms — covering photo carousels, video reels, and mixed content types. It tracks gym submissions and social posting status. This is the most functional and up-to-date content tracker, worth keeping.",
        group: "content-hub",
      },
      {
        id: 18,
        name: "Content Hub - Document Manager",
        url: "https://tiujeaef.manus.space",
        dateDeployed: "Jul 3, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A comprehensive document manager for gymnastics content organized into categories: Curriculum & Training, Marketing & Social Media, Business Strategy, Preschool Programs, and Technical Skills. It's the cleanest single-panel document manager in the group. Keep this as your primary document hub.",
        group: "content-hub",
      },
      {
        id: 19,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://etpcjrtk.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "The best version of the Universal Content Management System, featuring a structured content library with implementation guides, interactive games, a prize system, and detailed content pieces with ROI metrics. This is the most feature-rich of the many Universal CMS versions. Keep this one and delete all the duplicates.",
        group: "content-hub",
      },
      {
        id: 20,
        name: "Marketing Content Database - Browse & Discover Ideas",
        url: "https://dkvbrrcz.manus.space",
        dateDeployed: "Jun 5, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A curated database of 30+ social media content ideas for gymnastics clubs, with categories, target audiences, skill levels, and advanced filtering. This is a unique browsable idea library that serves a different purpose from the document managers. Worth keeping.",
        group: "content-hub",
      },
      {
        id: 21,
        name: "Gymnastics Social Media Content Hub",
        url: "https://tmofynkc.manus.space",
        dateDeployed: "May 22, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A large collection of 300+ content ideas for gymnastics clubs covering energy management, brain development, life skills, and authentic community content. This is the original and most complete version of the social media content hub. Keep this one and delete the duplicates.",
        group: "content-hub",
      },
      {
        id: 22,
        name: "Website - qzfsfrzz",
        url: "https://qzfsfrzz.manus.space",
        dateDeployed: "Aug 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A duplicate of the Gym Content Manager above, deployed on the same day with the same dashboard, content tracker, and gym shortcuts. There is no functional difference between the two. Delete this one and keep kkgpsidz.",
        group: "content-hub",
      },
      {
        id: 23,
        name: "Document Hub - Manage Documents & Notes",
        url: "https://xfbcxcia.manus.space",
        dateDeployed: "Jul 9, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A duplicate document hub with the same categories and layout as the Content Hub - Document Manager (tiujeaef). It was likely an intermediate build before the final version was settled. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 24,
        name: "Document Hub - Manage Documents & Notes",
        url: "https://ppwamljw.manus.space",
        dateDeployed: "Jul 9, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A second duplicate of the document hub, identical to the xfbcxcia version deployed on the same day. Both are superseded by the cleaner tiujeaef version. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 25,
        name: "Content Hub - Three Panel Document Manager",
        url: "https://favyfoih.manus.space",
        dateDeployed: "Jul 3, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A three-panel layout version of the document manager, deployed on the same day as the final single-panel version. The three-panel design was an experimental layout that was ultimately replaced. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 26,
        name: "Content Hub - Three Panel Document Manager",
        url: "https://tmblzllx.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An earlier three-panel document manager that included an AI Notes feature. This was part of the iterative development of the document hub layout. Superseded by the Jul 3 final version.",
        group: "content-hub",
      },
      {
        id: 27,
        name: "Content Hub - Three Panel Document Manager",
        url: "https://yhrppgsn.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Another Jul 2 three-panel document manager with a document viewer and AI notes panel. One of several builds from the same development session. Duplicate — safe to delete.",
        group: "content-hub",
      },
      {
        id: 28,
        name: "Content Hub - Three Panel Document Manager",
        url: "https://oogtemmk.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A minimal three-panel content hub from the same Jul 2 development session. It has the same structure as the other three-panel versions but with less content. Duplicate — safe to delete.",
        group: "content-hub",
      },
      {
        id: 29,
        name: "Gymnastics Content Hub - Ultimate Document Management System",
        url: "https://lodkwmch.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A comprehensive document management system with search, categories, and AI-enhanced content, deployed Jul 2. It was superseded the very next day by the cleaner tiujeaef version. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 30,
        name: "Gymnastics Content Hub - Ultimate Document Management System",
        url: "https://dwzuxoko.manus.space",
        dateDeployed: "Jul 1, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An earlier Jul 1 version of the Ultimate Document Management System. It was quickly followed by multiple newer versions the next day. Duplicate — safe to delete.",
        group: "content-hub",
      },
      {
        id: 31,
        name: "https://snkvyacw.manus.space",
        url: "https://snkvyacw.manus.space",
        dateDeployed: "Jul 1, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An unnamed content creation system that outlines the EPIC Content Formula and viral content strategies. While the content is interesting, it significantly overlaps with other content hubs and has no unique name. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 32,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://lyyikbyq.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A duplicate of the Universal CMS catalog (etpcjrtk) deployed on the same day. It has the same content library, interactive games, and prize system. Keep etpcjrtk and delete this one.",
        group: "content-hub",
      },
      {
        id: 33,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://axlktylf.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Another duplicate of the Universal CMS catalog from the Jun 27 development session. Identical content and structure to the primary version. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 34,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://fggligqo.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "One of several identical Universal CMS duplicates deployed on Jun 27. No functional difference from the primary version. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 35,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://uatrppyy.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "One of several identical Universal CMS duplicates deployed on Jun 27. No functional difference from the primary version. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 36,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://kekwfdyo.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "One of several identical Universal CMS duplicates deployed on Jun 27. No functional difference from the primary version. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 37,
        name: "August Content Dashboard - Gymnastics Interactive Content System",
        url: "https://jvkkzugm.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A month-specific content dashboard built for August, featuring ready-to-post content, interactive games, and a prize system. While it was functional, it was superseded by the more general Gym Content Manager. Month-specific dashboards are better managed within a general system.",
        group: "content-hub",
      },
      {
        id: 38,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://onpesmaj.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "One of several identical Universal CMS duplicates deployed on Jun 27. No functional difference from the primary version. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 39,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://wdfstksn.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "One of several identical Universal CMS duplicates deployed on Jun 27. No functional difference from the primary version. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 40,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://sqqyumzr.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "One of several identical Universal CMS duplicates deployed on Jun 27. No functional difference from the primary version. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 41,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://sojqkfsc.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "One of several identical Universal CMS duplicates deployed on Jun 27. No functional difference from the primary version. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 42,
        name: "gymnastics-content-hub",
        url: "https://zdeglbqq.manus.space",
        dateDeployed: "Jun 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A 300+ content ideas hub deployed in June, which is a duplicate of the May 22 tmofynkc version. The content is the same social media idea library. Keep the original tmofynkc and delete this one.",
        group: "content-hub",
      },
      {
        id: 43,
        name: "Website - maymnxvn",
        url: "https://maymnxvn.manus.space",
        dateDeployed: "Jun 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An unnamed social media content hub for gymnastics deployed on the same day as zdeglbqq. It has the same 300+ content ideas as the original. Duplicate — safe to delete.",
        group: "content-hub",
      },
      {
        id: 44,
        name: "Gymnastics Social Media & Ambassador Program Hub",
        url: "https://eeejwfpc.manus.space",
        dateDeployed: "Jun 11, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A strategy package covering viral content creation and an ambassador program for gymnastics clubs. While it has some unique ambassador program content, it significantly overlaps with the other content hubs. The content could be folded into the primary hub.",
        group: "content-hub",
      },
      {
        id: 45,
        name: "Website - tgqdoftj",
        url: "https://tgqdoftj.manus.space",
        dateDeployed: "Jun 5, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A marketing content database with social media ideas, deployed the same day as the dkvbrrcz version. It is a duplicate of that database with the same browsable idea library. Keep dkvbrrcz and delete this one.",
        group: "content-hub",
      },
      {
        id: 46,
        name: "gymnastics-content-hub",
        url: "https://vrdydjjb.manus.space",
        dateDeployed: "May 22, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A duplicate of the tmofynkc gymnastics content hub deployed on the same day. It contains the same 300+ content ideas and categories. Keep tmofynkc and delete this one.",
        group: "content-hub",
      },
      {
        id: 47,
        name: "Website - ljaqwoov",
        url: "https://ljaqwoov.manus.space",
        dateDeployed: "May 19, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A gymnastics marketing hub with task management and a content calendar, deployed in May. It overlaps significantly with the gymnect-dashboard and later content managers. An early prototype that has been superseded.",
        group: "content-hub",
      },
      {
        id: 48,
        name: "Website - qrjvpwdb",
        url: "https://qrjvpwdb.manus.space",
        dateDeployed: "May 19, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A gymnastics marketing hub dashboard deployed on the same day as ljaqwoov. It is a duplicate of that version with the same task management and calendar features. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 49,
        name: "Website - vsbxucft",
        url: "https://vsbxucft.manus.space",
        dateDeployed: "Apr 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An early prototype of a gymnastics events calendar that was designed to sync with iClass portals. This was one of the first tools built and has been fully superseded by later, more comprehensive content managers. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 50,
        name: "gymnect-dashboard",
        url: "https://kbhqniag.manus.space",
        dateDeployed: "Apr 10, 2025",
        status: "Published",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "The earliest gymnastics marketing dashboard, dating back to April 2025. It is a work-in-progress with incomplete features and a rough layout. All of its functionality has been rebuilt and improved in later versions. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 51,
        name: "Website - w5hni7comg5p",
        url: "https://w5hni7comg5p.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "A raw document dump containing a mix of gymnastics and unrelated technical files. This appears to be a development artifact from a build session, not an intentional user-facing site. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 52,
        name: "Website - mzhyi8cdl89k",
        url: "https://mzhyi8cdl89k.manus.space",
        dateDeployed: "Aug 12, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "A user API test interface — essentially a backend testing tool that was accidentally deployed as a public site. It is not a user-facing product and has no content for end users. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 53,
        name: "gym-content-system",
        url: "https://p9hwiqcnvkqo.manus.space",
        dateDeployed: "Aug 18, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "Another user API test interface for the gym content system backend. Like the mzhyi8cdl89k site, this is a development artifact that was deployed publicly by mistake. Not a user-facing product.",
        group: "content-hub",
      },
      {
        id: 54,
        name: "Website - vgh0i1c5xpk1",
        url: "https://vgh0i1c5xpk1.manus.space",
        dateDeployed: "Aug 12, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "A user API test interface for the gym content manager backend, similar to the other API test sites. It was deployed as part of the backend development process and is not intended for end users. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 55,
        name: "gym-content-backend",
        url: "https://g8h3ilc3v1xg.manus.space",
        dateDeployed: "Aug 31, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "A backend API testing interface for user management CRUD operations. This is a development/debugging tool that should never have been left as a public deployment. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 56,
        name: "Website - cmlqdkit",
        url: "https://cmlqdkit.manus.space",
        dateDeployed: "Jul 3, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A document manager for gymnastics content with the same categories as the Content Hub - Document Manager (tiujeaef). It was deployed on the same day as the final version and is a duplicate. Safe to delete.",
        group: "content-hub",
      },
      {
        id: 57,
        name: "https://0vhlizcpw517.manus.space",
        url: "https://0vhlizcpw517.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An unnamed gymnastics content hub with search, categories, and AI-enhanced document features. It is a duplicate of the other Jul 2 content hub builds. No unique name or purpose — safe to delete.",
        group: "content-hub",
      },
      {
        id: 58,
        name: "July Social Media Content Planner",
        url: "https://raokdloh.manus.space",
        dateDeployed: "Jul 10, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A month-specific document hub built for July content planning. Like the August dashboard, it has been superseded by the general Gym Content Manager which handles all months. Month-specific sites create unnecessary clutter.",
        group: "content-hub",
      },
    ],
  },

  // ─── EMAIL HUB / BUILDER ─────────────────────────────────────────────────
  {
    id: "email-hub",
    name: "Email Hub / Builder",
    description: "Email approval workflows, email builders, and marketing strategy tools for gymnastics clubs.",
    sites: [
      {
        id: 59,
        name: "Ultimate Gym Email System",
        url: "https://ultimate-zzuf3c.manus.space",
        dateDeployed: "Sep 14, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "An email generation system with pre-designed templates including Quiz, Monthly Events Newsletter, and Back to School Special. You can select specific gyms and customize the output. This is a functional, polished tool worth keeping.",
        group: "email-hub",
      },
      {
        id: 60,
        name: "Gymnastics Email Marketing Hub",
        url: "https://gymnastics-hub-heddwwk8.manus.space",
        dateDeployed: "Oct 30, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A data-backed email marketing strategy resource for recreational gymnastics clubs. It covers core strategies, a campaign library, design excellence principles, and audience intelligence. This is a reference/strategy hub rather than a builder, making it a unique and useful resource.",
        group: "email-hub",
      },
      {
        id: 61,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://qpzjmceezkkwdssw.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "The most functional Email Approval Hub, managing email status (Pending Review, Sent/Live, Needs Edits, Overdue) across multiple gymnastics academies. It provides a clear workflow for tracking which emails have been approved and sent. This is the primary version to keep.",
        group: "email-hub",
      },
      {
        id: 62,
        name: "Website - hhwjsrqxyylvpwic",
        url: "https://hhwjsrqxyylvpwic.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A duplicate Email Approval Hub preview with the same functionality as the primary version (qpzjmceezkkwdssw). It was deployed in the same session as part of iterative testing. Safe to delete.",
        group: "email-hub",
      },
      {
        id: 63,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://kxmckglzgshpzbgx.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A duplicate Email Approval Hub preview from the same Aug 28 development session. It has the same content and approval workflow as the primary version. Safe to delete.",
        group: "email-hub",
      },
      {
        id: 64,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://knsvzwwhzbojfyrq.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Another duplicate Email Approval Hub preview from the Aug 28 session. No functional difference from the primary version. Safe to delete.",
        group: "email-hub",
      },
      {
        id: 65,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://uzzxgcaclhzklehw.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "A duplicate Email Approval Hub that appears to be specifically configured for Capital Gymnastics branches. Since this is a preview/test version and the primary hub covers all academies, this one can be safely deleted.",
        group: "email-hub",
      },
      {
        id: 66,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://xxugtqcunpgpryjo.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Another duplicate Email Approval Hub preview from the Aug 28 session. No functional difference from the primary version. Safe to delete.",
        group: "email-hub",
      },
      {
        id: 67,
        name: "Website - xyzwvbkqtathemcx",
        url: "https://xyzwvbkqtathemcx.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "An unnamed Email Approval Hub preview from the same Aug 28 session. The generic name and duplicate content confirm this was a test deployment. Safe to delete.",
        group: "email-hub",
      },
      {
        id: 68,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://kznzxwolpilcmwax.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "The final duplicate Email Approval Hub preview from the Aug 28 session. No functional difference from the primary version. Safe to delete.",
        group: "email-hub",
      },
    ],
  },

  // ─── LEAD MANAGEMENT ─────────────────────────────────────────────────────
  {
    id: "lead-management",
    name: "Lead Management",
    description: "Lead tracking and management systems for gymnastics club enrollment pipelines.",
    sites: [
      {
        id: 69,
        name: "Lead Management Intelligence System - Scottsdale Gymnastics",
        url: "https://leadmanag-aavzrr.manus.space",
        dateDeployed: "Sep 25, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A real-time lead tracking system built specifically for Scottsdale Gymnastics. It lets you view lead profiles, track call progress, manage telethon actions, and filter leads by interest categories. This is a functional and unique tool — keep it.",
        group: "lead-management",
      },
      {
        id: 70,
        name: "Capital Gymnastics Lead Manager",
        url: "https://capgym-ccbyno.manus.space",
        dateDeployed: "Sep 12, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "This site displays a connection error due to a database configuration issue and cannot load any content. It was intended to be a lead manager for Capital Gymnastics but is completely non-functional. Safe to delete.",
        group: "lead-management",
      },
    ],
  },

  // ─── CAMP HUB ─────────────────────────────────────────────────────────────
  {
    id: "camp-hub",
    name: "Camp Hub",
    description: "Interactive game and activity collections for gymnastics seasonal camps.",
    sites: [
      {
        id: 71,
        name: "Camp Hub",
        url: "https://camphub-ewwhqkte.manus.space",
        dateDeployed: "Oct 18, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A fully functional Camp Hub with Arts & Crafts and Games sections, providing interactive activities with detailed instructions and visual diagrams for camp staff. This is the most complete and polished version of the Camp Hub. Keep this one.",
        group: "camp-hub",
      },
      {
        id: 72,
        name: "Seasonal Camp Hub - Interactive Game Collection",
        url: "https://camphub-bqqwlz.manus.space",
        dateDeployed: "Oct 15, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "An earlier version of the Camp Hub from three days before the final version. It is currently a placeholder or under-development state with no visible content. Superseded by the Oct 18 version. Safe to delete.",
        group: "camp-hub",
      },
      {
        id: 73,
        name: "Interactive Camp Hub",
        url: "https://camphub-5cayny3z.manus.space",
        dateDeployed: "Dec 5, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "This site returns a 404 error and is completely non-functional. Despite being deployed in December, it never loaded correctly. Safe to delete immediately.",
        group: "camp-hub",
      },
    ],
  },

  // ─── GYMVISION CMS ────────────────────────────────────────────────────────
  {
    id: "gymvision",
    name: "GymVision CMS",
    description: "GymVision content management system for gymnastics organizations.",
    sites: [
      {
        id: 74,
        name: "GymVision - Content Management System",
        url: "https://jhojuwxm.manus.space",
        dateDeployed: "Aug 13, 2025",
        status: "Published",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "The primary, published version of the GymVision Content Management System. It is the most stable and complete version, marked as Published. This is the definitive GymVision CMS — keep this one.",
        group: "gymvision",
      },
      {
        id: 75,
        name: "GymVision - Content Management System",
        url: "https://emailapp-x5yuxs.manus.space",
        dateDeployed: "Aug 26, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "A non-functional duplicate of the GymVision CMS that is stuck on a loading screen and never renders any content. Despite being deployed after the primary version, it never worked correctly. Safe to delete.",
        group: "gymvision",
      },
    ],
  },

  // ─── OTHER / STANDALONE ───────────────────────────────────────────────────
  {
    id: "other",
    name: "Other / Standalone",
    description: "Unique standalone tools that don't belong to a larger project group.",
    sites: [
      {
        id: 76,
        name: "Degage Classical Conservatory - Studio Management System",
        url: "https://degage-studio-lchnvj9m.manus.space",
        dateDeployed: "Dec 20, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A studio management system built specifically for Degage Classical Conservatory, handling student records, contracts, and payments. This is completely separate from all the gymnastics projects and serves a different client entirely. Keep it.",
        group: "other",
      },
      {
        id: 77,
        name: "Task Master - Digital Task Management",
        url: "https://aqitegwr.manus.space",
        dateDeployed: "Jul 24, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A general-purpose digital task management tool with task overview, filtering by timeframe, and automation features. It is not gymnastics-specific and serves as a standalone productivity tool. Worth keeping as a unique utility.",
        group: "other",
      },
      {
        id: 78,
        name: "Marketing Genius - Gymnastics Club Campaign Generator",
        url: "https://gymgenius-swxzrdjt.manus.space",
        dateDeployed: "Nov 11, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "An AI-powered campaign generator for gymnastics clubs that creates customized marketing campaigns. This is a unique tool with no duplicate in your portfolio. Keep it as a standalone campaign creation resource.",
        group: "other",
      },
      {
        id: 79,
        name: "Gym Summer Camp Manager",
        url: "https://gymcampmgr-axf9zfid.manus.space",
        dateDeployed: "Nov 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A dedicated summer camp management tool for gyms with unique functionality for planning and running camp programs. It is distinct from the general content managers and the Camp Hub. Keep it as a specialized camp operations tool.",
        group: "other",
      },
      {
        id: 80,
        name: "Story Bundle - One Story, Many Lenses",
        url: "https://ftqdzyxo.manus.space",
        dateDeployed: "Jun 9, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "A unique content strategy tool for repurposing a single story across multiple content formats and perspectives. It helps you get maximum mileage from one piece of content by viewing it through different lenses. No duplicate exists — keep it.",
        group: "other",
      },
    ],
  },

  // ─── BLANK / ERROR / INACCESSIBLE ────────────────────────────────────────
  {
    id: "blank-error",
    name: "Blank / Error / Inaccessible",
    description: "Sites that are blank, return errors, or are completely inaccessible. All safe to delete.",
    sites: [
      {
        id: 81,
        name: "EmailForge - Creative Email Vision Generator",
        url: "https://emailforge-n9dplkgf.manus.space",
        dateDeployed: "Jan 13, 2026",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error and is completely non-functional. Despite being the most recently deployed site on the list, it never loaded correctly. The name suggests it was intended as an email generation tool, but it was never completed.",
        group: "blank-error",
      },
      {
        id: 82,
        name: "Internal Trial Finder",
        url: "https://trialfindr-hupbutej.manus.space",
        dateDeployed: "Dec 28, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error and is completely non-functional. The name suggests it was intended to help find trial class leads internally, but the site was never completed or deployed successfully.",
        group: "blank-error",
      },
      {
        id: 83,
        name: "Gymnastics Email Builder Pro",
        url: "https://gymnastics-email-nmic5efc.manus.space",
        dateDeployed: "Dec 18, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error and is completely non-functional. It was likely an early attempt at an email builder that was abandoned in favor of the Ultimate Gym Email System. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 84,
        name: "Gym Social Campaign Manager",
        url: "https://gymcampaign-nw5zdwzw.manus.space",
        dateDeployed: "Dec 7, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error and is completely non-functional. The name suggests it was intended as a social media campaign management tool, but it was never successfully deployed. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 85,
        name: "Gym Image Manager",
        url: "https://gymimgr-auyo6jdc.manus.space",
        dateDeployed: "Dec 5, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error and is completely non-functional. It was likely intended as an image management tool for gym content but was never completed. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 86,
        name: "Holiday Hustle",
        url: "https://holihustle-8zbw6y9w.manus.space",
        dateDeployed: "Nov 7, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "A blank placeholder page with no content or functionality. Despite being public, there is nothing on this site. The name suggests a holiday marketing campaign tool that was never built out. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 87,
        name: "AI Resume Builder Pro",
        url: "https://airesumebld-t8wfrzen.manus.space",
        dateDeployed: "Oct 31, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error and is completely non-functional. This appears to be an unrelated side project that was never completed. It has no connection to the gymnastics projects. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 88,
        name: "Camp Pricing Reference",
        url: "https://campprice-nyt3xt7t.manus.space",
        dateDeployed: "Oct 30, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error and is completely non-functional. It was likely intended as a quick pricing reference tool for camp enrollment but was never successfully deployed. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 89,
        name: "Email Approval Hub",
        url: "https://emailapp-kk69lo.manus.space",
        dateDeployed: "Sep 2, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Displays a 'Failed to load data from database' error and cannot show any content. This was an early version of the Email Approval Hub that had a broken database connection. The functional version (qpzjmceezkkwdssw) replaced it. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 90,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://emailapp-m2nw5p.manus.space",
        dateDeployed: "Aug 27, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Displays a 'website has been set to unavailable' message and cannot be accessed. This was an intermediate version of the Email Approval Hub that was taken offline. The functional version (qpzjmceezkkwdssw) is the one to keep.",
        group: "blank-error",
      },
      {
        id: 91,
        name: "Website - hktnwesl",
        url: "https://hktnwesl.manus.space",
        dateDeployed: "Aug 18, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns an HTTP error and is completely inaccessible. The generic name and error state suggest this was a failed deployment from a development session. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 92,
        name: "Website - pmeflbqg",
        url: "https://pmeflbqg.manus.space",
        dateDeployed: "Aug 18, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error and is completely non-functional. Deployed on the same day as hktnwesl, this appears to be another failed deployment from the same session. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 93,
        name: "https://8xhpiqcq06j9.manus.space",
        url: "https://8xhpiqcq06j9.manus.space",
        dateDeployed: "Aug 13, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "An unnamed site that is non-functional or blank. It has no title, no content, and no clear purpose. Likely a failed or abandoned deployment from the August development session. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 94,
        name: "Gymnastics Content Hub - Ultimate Document Management",
        url: "https://yptfivjl.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "A blank or incorrectly loaded version of the Ultimate Document Management System from the Jul 2 development session. It never rendered its content correctly. The functional version (tiujeaef) is the one to keep.",
        group: "blank-error",
      },
      {
        id: 95,
        name: "Gymnastics Content Hub - Ultimate Document Management",
        url: "https://ehgsyzbk.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Another blank or error version of the Ultimate Document Management System from the same Jul 2 session. Like yptfivjl, it never loaded correctly. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 96,
        name: "Content Hub - Three Panel Document Manager",
        url: "https://wjwyvyen.manus.space",
        dateDeployed: "Jul 3, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "A blank placeholder page with only a 'Made with Manus' footer and no actual content. Despite being deployed on the same day as the final document manager, this version never had any content added to it. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 97,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://aknhztnx.manus.space",
        dateDeployed: "Jul 8, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Set to unavailable and completely inaccessible. This is one of four Universal CMS versions from Jul 8 that were all set to private/unavailable. None of them are functional. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 98,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://ooikudds.manus.space",
        dateDeployed: "Jul 8, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Set to unavailable and completely inaccessible. One of four Universal CMS versions from Jul 8 that were all set to private/unavailable. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 99,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://chlkqhfd.manus.space",
        dateDeployed: "Jul 8, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Set to unavailable and completely inaccessible. One of four Universal CMS versions from Jul 8 that were all set to private/unavailable. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 100,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://tirgoxto.manus.space",
        dateDeployed: "Jul 8, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Set to unavailable and completely inaccessible. The last of four Universal CMS versions from Jul 8 that were all set to private/unavailable. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 101,
        name: "Gymnastics Content Mastery System",
        url: "https://hckjgffy.manus.space",
        dateDeployed: "Jun 21, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "A blank page with no visible content despite having a title. It was deployed publicly but never had any content added to it. The name suggests it was intended as a content mastery training system. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 102,
        name: "https://nbvzwngy.manus.space",
        url: "https://nbvzwngy.manus.space",
        dateDeployed: "Jun 5, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "A completely blank site with no content, no title, and no functionality. It was deployed on the same day as the Marketing Content Database but clearly never had anything added to it. Safe to delete immediately.",
        group: "blank-error",
      },
      {
        id: 103,
        name: "https://stfghtbn.manus.space",
        url: "https://stfghtbn.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "A blank or inaccessible site with no content or title. It was deployed on the same day as the many Universal CMS duplicates and appears to be another failed deployment from that session. Safe to delete.",
        group: "blank-error",
      },
      {
        id: 104,
        name: "https://snkvyacw.manus.space (duplicate)",
        url: "https://snkvyacw.manus.space",
        dateDeployed: "Jul 1, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "This entry is a duplicate of the snkvyacw site already listed in the Content Hub group. It appears twice in the deployed sites list, which is why it shows up here as well. Safe to delete — only one entry is needed.",
        group: "blank-error",
      },
    ],
  },
];

// Computed stats
export const allSites: Site[] = siteGroups.flatMap((g) => g.sites);

export const stats = {
  total: allSites.length,
  keep: allSites.filter((s) => s.recommendation === "Keep").length,
  delete: allSites.filter((s) => s.recommendation === "Delete").length,
  combine: allSites.filter((s) => s.recommendation === "Combine").length,
};
