// Design: Precision Ops Dashboard — Dark Mode Intelligence
// All 106 deployed websites organized by project group with recommendations

export type Recommendation = "Keep" | "Delete" | "Combine";
export type PolishLevel = "Polished" | "Draft/WIP" | "Blank/Error";

export interface Site {
  id: number;
  name: string;
  url: string;
  dateDeployed: string;
  status: "Public" | "Published" | "Private";
  polishLevel: PolishLevel;
  recommendation: Recommendation;
  purpose: string;
  group: string;
}

export interface SiteGroup {
  id: string;
  name: string;
  description: string;
  sites: Site[];
}

export const siteGroups: SiteGroup[] = [
  {
    id: "summer-camp",
    name: "Summer Camp Enrollment",
    description: "Comprehensive resource hub for summer camp enrollment training, guides, and communication tools.",
    sites: [
      {
        id: 1,
        name: "Summer Camp Enrollment Resources",
        url: "https://yfnbtxup.manus.space",
        dateDeployed: "May 18, 2025",
        status: "Published",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Most recent published version. Full enrollment hub with guides, interactive training, communication tools, and manager resources.",
        group: "summer-camp",
      },
      {
        id: 2,
        name: "Website - qqczrspc",
        url: "https://qqczrspc.manus.space",
        dateDeployed: "May 18, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Identical duplicate of the Summer Camp Enrollment Resources hub. Same content, same structure.",
        group: "summer-camp",
      },
      {
        id: 3,
        name: "Summer Camp Enrollment Resources",
        url: "https://bvpxezze.manus.space",
        dateDeployed: "May 17, 2025",
        status: "Published",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Older duplicate of the Summer Camp Enrollment Resources hub. Identical content to the May 18 version.",
        group: "summer-camp",
      },
    ],
  },
  {
    id: "sales-training",
    name: "Gymnastics Sales Training",
    description: "The Belief + Knowledge Sales System for Gymnastics — Windows & Doors conversation technique training.",
    sites: [
      {
        id: 4,
        name: "Sales Specialist Program Documentation",
        url: "https://salesdocs-5vzxrauk.manus.space",
        dateDeployed: "Dec 5, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Most comprehensive and recent version. Full 4-week pilot program, job descriptions, phone scripts, exercises, and metrics dashboard.",
        group: "sales-training",
      },
      {
        id: 5,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://uacswweo.manus.space",
        dateDeployed: "Jun 17, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Polished sales training site covering Windows & Doors technique, objection handling, and belief-building exercises. Superseded by newer version.",
        group: "sales-training",
      },
      {
        id: 6,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://edezylyo.manus.space",
        dateDeployed: "Jun 17, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Jun 17 sales training site. Same content and structure.",
        group: "sales-training",
      },
      {
        id: 7,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://zeqhkuyo.manus.space",
        dateDeployed: "Jun 11, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Earlier version of the sales system. Includes Jayme's Login feature but otherwise same content.",
        group: "sales-training",
      },
      {
        id: 8,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://hgifxcdo.manus.space",
        dateDeployed: "Jun 11, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Jun 11 sales training site. Identical content.",
        group: "sales-training",
      },
      {
        id: 9,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://vvoriwlm.manus.space",
        dateDeployed: "Jun 7, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Earlier version focused on introduction and belief-building exercises. Superseded.",
        group: "sales-training",
      },
      {
        id: 10,
        name: "Website - hwfdxjju",
        url: "https://hwfdxjju.manus.space",
        dateDeployed: "Jun 7, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Unnamed version of the sales system. Covers Windows & Doors analogy and core sections.",
        group: "sales-training",
      },
      {
        id: 11,
        name: "https://nvewbqrm.manus.space",
        url: "https://nvewbqrm.manus.space",
        dateDeployed: "Jun 7, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Another unnamed version of the sales system with full content including 70/30 Rule and YES-AND objection handling.",
        group: "sales-training",
      },
      {
        id: 12,
        name: "https://issmtfmr.manus.space",
        url: "https://issmtfmr.manus.space",
        dateDeployed: "Jun 7, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Unnamed version of the Belief + Knowledge Sales System. Duplicate content.",
        group: "sales-training",
      },
      {
        id: 13,
        name: "The Belief + Knowledge Sales System for Gymnastics",
        url: "https://ehtoxofz.manus.space",
        dateDeployed: "Jun 6, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Comprehensive early version with full Windows & Doors system, 70/30 Rule, and objection handling.",
        group: "sales-training",
      },
      {
        id: 14,
        name: "Create Next App",
        url: "https://gymnasticssalestraining.manus.space",
        dateDeployed: "Apr 16, 2025",
        status: "Published",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Earliest version of the gymnastics sales training system. Named 'Create Next App' — clearly a leftover from initial scaffolding.",
        group: "sales-training",
      },
      {
        id: 15,
        name: "ppjuivac.manus.space",
        url: "https://ppjuivac.manus.space",
        dateDeployed: "Apr 16, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Unnamed early version of the sales training system. Same content as the Apr 16 version.",
        group: "sales-training",
      },
    ],
  },
  {
    id: "content-hub",
    name: "Gymnastics Content Hub / CMS",
    description: "Content management systems, social media content databases, document hubs, and marketing catalogs for gymnastics.",
    sites: [
      {
        id: 16,
        name: "Ultimate Design Studio - Gymnastics Email Powerhouse",
        url: "https://ultdesign-pgp98n.manus.space",
        dateDeployed: "Sep 15, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Unique email design and generation platform. Allows selecting from FAQ, Quiz, and Complete templates, generating emails for specific gyms, and AI analysis.",
        group: "content-hub",
      },
      {
        id: 17,
        name: "Gym Content Manager",
        url: "https://kkgpsidz.manus.space",
        dateDeployed: "Aug 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Content management system for tracking monthly content assignments — photo carousels, video reels, mixed content — with gym submissions and social posting tracking.",
        group: "content-hub",
      },
      {
        id: 18,
        name: "Content Hub - Document Manager",
        url: "https://tiujeaef.manus.space",
        dateDeployed: "Jul 3, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Comprehensive document manager for gymnastics content organized by Curriculum & Training, Marketing & Social Media, Business Strategy, Preschool Programs, and Technical Skills.",
        group: "content-hub",
      },
      {
        id: 19,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://etpcjrtk.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Best version of the Universal CMS. Structured content library with implementation guides, interactive games, prize system, and detailed content pieces with ROI metrics.",
        group: "content-hub",
      },
      {
        id: 20,
        name: "Marketing Content Database - Browse & Discover Ideas",
        url: "https://dkvbrrcz.manus.space",
        dateDeployed: "Jun 5, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Curated database of 30+ social media content ideas for gymnastics with categories, audiences, levels, and advanced filtering.",
        group: "content-hub",
      },
      {
        id: 21,
        name: "Gymnastics Social Media Content Hub",
        url: "https://tmofynkc.manus.space",
        dateDeployed: "May 22, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "300+ content ideas for gymnastics clubs covering energy management, brain development, life skills, and authentic community content.",
        group: "content-hub",
      },
      {
        id: 22,
        name: "Website - qzfsfrzz",
        url: "https://qzfsfrzz.manus.space",
        dateDeployed: "Aug 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of Gym Content Manager. Same dashboard, content tracker, and gym shortcuts.",
        group: "content-hub",
      },
      {
        id: 23,
        name: "Document Hub - Manage Documents & Notes",
        url: "https://xfbcxcia.manus.space",
        dateDeployed: "Jul 9, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate document hub with same categories as the Content Hub - Document Manager.",
        group: "content-hub",
      },
      {
        id: 24,
        name: "Document Hub - Manage Documents & Notes",
        url: "https://ppwamljw.manus.space",
        dateDeployed: "Jul 9, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Second duplicate of the document hub. Identical to xfbcxcia version.",
        group: "content-hub",
      },
      {
        id: 25,
        name: "Content Hub - Three Panel Document Manager",
        url: "https://favyfoih.manus.space",
        dateDeployed: "Jul 3, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Three-panel layout version of the document manager. Superseded by the single-panel version.",
        group: "content-hub",
      },
      {
        id: 26,
        name: "Content Hub - Three Panel Document Manager",
        url: "https://tmblzllx.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Earlier three-panel document manager with AI Notes feature. Superseded.",
        group: "content-hub",
      },
      {
        id: 27,
        name: "Content Hub - Three Panel Document Manager",
        url: "https://yhrppgsn.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Three-panel document manager with document viewer and AI notes. Duplicate.",
        group: "content-hub",
      },
      {
        id: 28,
        name: "Content Hub - Three Panel Document Manager",
        url: "https://oogtemmk.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Minimal three-panel content hub. Duplicate of other three-panel versions.",
        group: "content-hub",
      },
      {
        id: 29,
        name: "Gymnastics Content Hub - Ultimate Document Management System",
        url: "https://lodkwmch.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Comprehensive document management system with search, categories, and AI-enhanced content. Superseded by newer versions.",
        group: "content-hub",
      },
      {
        id: 30,
        name: "Gymnastics Content Hub - Ultimate Document Management System",
        url: "https://dwzuxoko.manus.space",
        dateDeployed: "Jul 1, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Earlier version of the Ultimate Document Management System. Duplicate.",
        group: "content-hub",
      },
      {
        id: 31,
        name: "https://snkvyacw.manus.space",
        url: "https://snkvyacw.manus.space",
        dateDeployed: "Jul 1, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Ultimate Source of Truth content creation system. Outlines EPIC Content Formula and viral strategies. Overlaps with other content hubs.",
        group: "content-hub",
      },
      {
        id: 32,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://lyyikbyq.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Universal CMS catalog. Same content library, interactive games, and prize system.",
        group: "content-hub",
      },
      {
        id: 33,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://axlktylf.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Universal CMS catalog.",
        group: "content-hub",
      },
      {
        id: 34,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://fggligqo.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Universal CMS catalog.",
        group: "content-hub",
      },
      {
        id: 35,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://uatrppyy.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Universal CMS catalog.",
        group: "content-hub",
      },
      {
        id: 36,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://kekwfdyo.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Universal CMS catalog.",
        group: "content-hub",
      },
      {
        id: 37,
        name: "August Content Dashboard - Gymnastics Interactive Content System",
        url: "https://jvkkzugm.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Month-specific content dashboard for August. Ready-to-post content, interactive games, prize system. Superseded by the general Gym Content Manager.",
        group: "content-hub",
      },
      {
        id: 38,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://onpesmaj.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Universal CMS catalog.",
        group: "content-hub",
      },
      {
        id: 39,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://wdfstksn.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Universal CMS catalog.",
        group: "content-hub",
      },
      {
        id: 40,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://sqqyumzr.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Universal CMS catalog.",
        group: "content-hub",
      },
      {
        id: 41,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://sojqkfsc.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the Universal CMS catalog.",
        group: "content-hub",
      },
      {
        id: 42,
        name: "gymnastics-content-hub",
        url: "https://zdeglbqq.manus.space",
        dateDeployed: "Jun 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "300+ content ideas hub. Duplicate of the May 22 version.",
        group: "content-hub",
      },
      {
        id: 43,
        name: "Website - maymnxvn",
        url: "https://maymnxvn.manus.space",
        dateDeployed: "Jun 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Unnamed social media content hub for gymnastics. Duplicate of the gymnastics-content-hub.",
        group: "content-hub",
      },
      {
        id: 44,
        name: "Gymnastics Social Media & Ambassador Program Hub",
        url: "https://eeejwfpc.manus.space",
        dateDeployed: "Jun 11, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Strategy package for viral content and ambassador program. Overlaps with other content hubs.",
        group: "content-hub",
      },
      {
        id: 45,
        name: "Website - tgqdoftj",
        url: "https://tgqdoftj.manus.space",
        dateDeployed: "Jun 5, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Marketing content database with social media ideas. Duplicate of the dkvbrrcz version.",
        group: "content-hub",
      },
      {
        id: 46,
        name: "gymnastics-content-hub",
        url: "https://vrdydjjb.manus.space",
        dateDeployed: "May 22, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate of the tmofynkc gymnastics content hub. Same 300+ content ideas.",
        group: "content-hub",
      },
      {
        id: 47,
        name: "Website - ljaqwoov",
        url: "https://ljaqwoov.manus.space",
        dateDeployed: "May 19, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Gymnastics marketing hub with task management and calendar. Overlaps with gymnect-dashboard.",
        group: "content-hub",
      },
      {
        id: 48,
        name: "Website - qrjvpwdb",
        url: "https://qrjvpwdb.manus.space",
        dateDeployed: "May 19, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Gymnastics marketing hub dashboard. Duplicate of ljaqwoov version.",
        group: "content-hub",
      },
      {
        id: 49,
        name: "Website - vsbxucft",
        url: "https://vsbxucft.manus.space",
        dateDeployed: "Apr 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Gymnastics Events Calendar synced with iClass portals. Early prototype, superseded.",
        group: "content-hub",
      },
      {
        id: 50,
        name: "gymnect-dashboard",
        url: "https://kbhqniag.manus.space",
        dateDeployed: "Apr 10, 2025",
        status: "Published",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "Early gym marketing dashboard. Work-in-progress with incomplete features. Superseded by newer content managers.",
        group: "content-hub",
      },
      {
        id: 51,
        name: "Website - w5hni7comg5p",
        url: "https://w5hni7comg5p.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "Raw document dump with mixed gymnastics and unrelated technical files. Appears to be a development artifact.",
        group: "content-hub",
      },
      {
        id: 52,
        name: "Website - mzhyi8cdl89k",
        url: "https://mzhyi8cdl89k.manus.space",
        dateDeployed: "Aug 12, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "User API test interface. Development/backend testing artifact, not a user-facing site.",
        group: "content-hub",
      },
      {
        id: 53,
        name: "gym-content-system",
        url: "https://p9hwiqcnvkqo.manus.space",
        dateDeployed: "Aug 18, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "User API test interface for gym content system. Development artifact.",
        group: "content-hub",
      },
      {
        id: 54,
        name: "Website - vgh0i1c5xpk1",
        url: "https://vgh0i1c5xpk1.manus.space",
        dateDeployed: "Aug 12, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "User API test interface for gym content manager. Development artifact.",
        group: "content-hub",
      },
      {
        id: 55,
        name: "gym-content-backend",
        url: "https://g8h3ilc3v1xg.manus.space",
        dateDeployed: "Aug 31, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "Backend API testing interface for user management CRUD operations. Development artifact.",
        group: "content-hub",
      },
      {
        id: 56,
        name: "Website - cmlqdkit",
        url: "https://cmlqdkit.manus.space",
        dateDeployed: "Jul 3, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Document manager for gymnastics content. Duplicate of the Content Hub - Document Manager.",
        group: "content-hub",
      },
      {
        id: 57,
        name: "https://0vhlizcpw517.manus.space",
        url: "https://0vhlizcpw517.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Unnamed gymnastics content hub with search, categories, and AI-enhanced documents. Duplicate.",
        group: "content-hub",
      },
      {
        id: 58,
        name: "July Social Media Content Planner",
        url: "https://raokdloh.manus.space",
        dateDeployed: "Jul 10, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Month-specific document hub for July content. Superseded by the general Gym Content Manager.",
        group: "content-hub",
      },
    ],
  },
  {
    id: "email-hub",
    name: "Email Hub / Builder",
    description: "Email approval workflows, email builders, and marketing strategy tools for gymnastics clubs.",
    sites: [
      {
        id: 59,
        name: "Ultimate Gym Email System",
        url: "https://ultimate-zzuf3c.manus.space",
        dateDeployed: "Sep 14, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Email generation system with pre-designed templates: Quiz, Monthly Events Newsletter, Back to School Special. Select gyms and customize.",
        group: "email-hub",
      },
      {
        id: 60,
        name: "Gymnastics Email Marketing Hub",
        url: "https://gymnastics-hub-heddwwk8.manus.space",
        dateDeployed: "Oct 30, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Data-backed email marketing strategies for recreational gymnastics clubs. Covers core strategies, campaign library, design excellence, and audience intelligence.",
        group: "email-hub",
      },
      {
        id: 61,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://qpzjmceezkkwdssw.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Most functional Email Approval Hub. Manages email status (Pending Review, Sent/Live, Needs Edits, Overdue) across multiple gymnastics academies.",
        group: "email-hub",
      },
      {
        id: 62,
        name: "Website - hhwjsrqxyylvpwic",
        url: "https://hhwjsrqxyylvpwic.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate Email Approval Hub. Same functionality as the primary version.",
        group: "email-hub",
      },
      {
        id: 63,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://kxmckglzgshpzbgx.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate Email Approval Hub preview. Same content and functionality.",
        group: "email-hub",
      },
      {
        id: 64,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://knsvzwwhzbojfyrq.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate Email Approval Hub preview.",
        group: "email-hub",
      },
      {
        id: 65,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://uzzxgcaclhzklehw.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate Email Approval Hub — this version is specifically for Capital Gymnastics branches.",
        group: "email-hub",
      },
      {
        id: 66,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://xxugtqcunpgpryjo.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate Email Approval Hub preview.",
        group: "email-hub",
      },
      {
        id: 67,
        name: "Website - xyzwvbkqtathemcx",
        url: "https://xyzwvbkqtathemcx.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Unnamed Email Approval Hub preview. Duplicate.",
        group: "email-hub",
      },
      {
        id: 68,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://kznzxwolpilcmwax.manus-preview.space",
        dateDeployed: "Aug 28, 2025",
        status: "Private",
        polishLevel: "Polished",
        recommendation: "Delete",
        purpose: "Duplicate Email Approval Hub preview.",
        group: "email-hub",
      },
    ],
  },
  {
    id: "lead-management",
    name: "Lead Management",
    description: "Lead tracking and management systems for gymnastics club enrollment pipelines.",
    sites: [
      {
        id: 69,
        name: "Lead Management Intelligence System - Scottsdale Gymnastics",
        url: "https://leadmanag-aavzrr.manus.space",
        dateDeployed: "Sep 25, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Real-time lead tracking for Scottsdale Gymnastics. View lead profiles, track call progress, manage telethon actions, and filter by interest categories.",
        group: "lead-management",
      },
      {
        id: 70,
        name: "Capital Gymnastics Lead Manager",
        url: "https://capgym-ccbyno.manus.space",
        dateDeployed: "Sep 12, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Non-functional — displays a connection error due to database configuration issue. Cannot load any content.",
        group: "lead-management",
      },
    ],
  },
  {
    id: "camp-hub",
    name: "Camp Hub",
    description: "Interactive game and activity collections for gymnastics seasonal camps.",
    sites: [
      {
        id: 71,
        name: "Camp Hub",
        url: "https://camphub-ewwhqkte.manus.space",
        dateDeployed: "Oct 18, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Fully functional Camp Hub with Arts & Crafts and Games sections. Provides interactive activities with detailed instructions and visual diagrams.",
        group: "camp-hub",
      },
      {
        id: 72,
        name: "Seasonal Camp Hub - Interactive Game Collection",
        url: "https://camphub-bqqwlz.manus.space",
        dateDeployed: "Oct 15, 2025",
        status: "Public",
        polishLevel: "Draft/WIP",
        recommendation: "Delete",
        purpose: "Earlier version of the Camp Hub. Currently a placeholder/under development with no visible content.",
        group: "camp-hub",
      },
      {
        id: 73,
        name: "Interactive Camp Hub",
        url: "https://camphub-5cayny3z.manus.space",
        dateDeployed: "Dec 5, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error. Non-functional.",
        group: "camp-hub",
      },
    ],
  },
  {
    id: "gymvision",
    name: "GymVision CMS",
    description: "GymVision content management system for gymnastics organizations.",
    sites: [
      {
        id: 74,
        name: "GymVision - Content Management System",
        url: "https://jhojuwxm.manus.space",
        dateDeployed: "Aug 13, 2025",
        status: "Published",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Published GymVision CMS. The primary, most stable version of the GymVision content management system.",
        group: "gymvision",
      },
      {
        id: 75,
        name: "GymVision - Content Management System",
        url: "https://emailapp-x5yuxs.manus.space",
        dateDeployed: "Aug 26, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Not loading — stuck on a loading screen. Non-functional duplicate.",
        group: "gymvision",
      },
    ],
  },
  {
    id: "other",
    name: "Other / Standalone",
    description: "Unique standalone tools that don't belong to a larger project group.",
    sites: [
      {
        id: 76,
        name: "Degage Classical Conservatory - Studio Management System",
        url: "https://degage-studio-lchnvj9m.manus.space",
        dateDeployed: "Dec 20, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Studio management system for Degage Classical Conservatory. Handles student records, contracts, and payments. Completely separate from gymnastics projects.",
        group: "other",
      },
      {
        id: 77,
        name: "Task Master - Digital Task Management",
        url: "https://aqitegwr.manus.space",
        dateDeployed: "Jul 24, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "General-purpose digital task management tool with task overview, filtering by timeframe, and automation features.",
        group: "other",
      },
      {
        id: 78,
        name: "Marketing Genius - Gymnastics Club Campaign Generator",
        url: "https://gymgenius-swxzrdjt.manus.space",
        dateDeployed: "Nov 11, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "AI-powered campaign generator for gymnastics clubs. Unique tool for generating marketing campaigns.",
        group: "other",
      },
      {
        id: 79,
        name: "Gym Summer Camp Manager",
        url: "https://gymcampmgr-axf9zfid.manus.space",
        dateDeployed: "Nov 12, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Dedicated summer camp management tool for gyms. Unique functionality separate from the general content managers.",
        group: "other",
      },
      {
        id: 80,
        name: "Story Bundle - One Story, Many Lenses",
        url: "https://ftqdzyxo.manus.space",
        dateDeployed: "Jun 9, 2025",
        status: "Public",
        polishLevel: "Polished",
        recommendation: "Keep",
        purpose: "Unique content strategy tool for repurposing a single story across multiple content formats and lenses.",
        group: "other",
      },
    ],
  },
  {
    id: "blank-error",
    name: "Blank / Error / Inaccessible",
    description: "Sites that are blank, return errors, or are completely inaccessible. Safe to delete.",
    sites: [
      {
        id: 81,
        name: "EmailForge - Creative Email Vision Generator",
        url: "https://emailforge-n9dplkgf.manus.space",
        dateDeployed: "Jan 13, 2026",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error. Non-functional.",
        group: "blank-error",
      },
      {
        id: 82,
        name: "Internal Trial Finder",
        url: "https://trialfindr-hupbutej.manus.space",
        dateDeployed: "Dec 28, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error. Non-functional.",
        group: "blank-error",
      },
      {
        id: 83,
        name: "Gymnastics Email Builder Pro",
        url: "https://gymnastics-email-nmic5efc.manus.space",
        dateDeployed: "Dec 18, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error. Non-functional.",
        group: "blank-error",
      },
      {
        id: 84,
        name: "Gym Social Campaign Manager",
        url: "https://gymcampaign-nw5zdwzw.manus.space",
        dateDeployed: "Dec 7, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error. Non-functional.",
        group: "blank-error",
      },
      {
        id: 85,
        name: "Gym Image Manager",
        url: "https://gymimgr-auyo6jdc.manus.space",
        dateDeployed: "Dec 5, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error. Non-functional.",
        group: "blank-error",
      },
      {
        id: 86,
        name: "Holiday Hustle",
        url: "https://holihustle-8zbw6y9w.manus.space",
        dateDeployed: "Nov 7, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Blank placeholder page with no content or functionality.",
        group: "blank-error",
      },
      {
        id: 87,
        name: "AI Resume Builder Pro",
        url: "https://airesumebld-t8wfrzen.manus.space",
        dateDeployed: "Oct 31, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error. Non-functional.",
        group: "blank-error",
      },
      {
        id: 88,
        name: "Camp Pricing Reference",
        url: "https://campprice-nyt3xt7t.manus.space",
        dateDeployed: "Oct 30, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error. Non-functional.",
        group: "blank-error",
      },
      {
        id: 89,
        name: "Email Approval Hub",
        url: "https://emailapp-kk69lo.manus.space",
        dateDeployed: "Sep 2, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Displays 'Failed to load data from database' error. Non-functional.",
        group: "blank-error",
      },
      {
        id: 90,
        name: "Email Approval Hub - GymVision Content Management",
        url: "https://emailapp-m2nw5p.manus.space",
        dateDeployed: "Aug 27, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Displays 'website has been set to unavailable' message. Non-functional.",
        group: "blank-error",
      },
      {
        id: 91,
        name: "Website - hktnwesl",
        url: "https://hktnwesl.manus.space",
        dateDeployed: "Aug 18, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns HTTP error. Non-functional.",
        group: "blank-error",
      },
      {
        id: 92,
        name: "Website - pmeflbqg",
        url: "https://pmeflbqg.manus.space",
        dateDeployed: "Aug 18, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Returns a 404 error. Non-functional.",
        group: "blank-error",
      },
      {
        id: 93,
        name: "https://8xhpiqcq06j9.manus.space",
        url: "https://8xhpiqcq06j9.manus.space",
        dateDeployed: "Aug 13, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Unnamed site. Non-functional or blank.",
        group: "blank-error",
      },
      {
        id: 94,
        name: "Gymnastics Content Hub - Ultimate Document Management",
        url: "https://yptfivjl.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Blank or did not load correctly. Non-functional.",
        group: "blank-error",
      },
      {
        id: 95,
        name: "Gymnastics Content Hub - Ultimate Document Management",
        url: "https://ehgsyzbk.manus.space",
        dateDeployed: "Jul 2, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Blank or error page. Non-functional.",
        group: "blank-error",
      },
      {
        id: 96,
        name: "Content Hub - Three Panel Document Manager",
        url: "https://wjwyvyen.manus.space",
        dateDeployed: "Jul 3, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Blank placeholder page with only a 'Made with Manus' footer. No content.",
        group: "blank-error",
      },
      {
        id: 97,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://aknhztnx.manus.space",
        dateDeployed: "Jul 8, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Set to unavailable. Non-functional.",
        group: "blank-error",
      },
      {
        id: 98,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://ooikudds.manus.space",
        dateDeployed: "Jul 8, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Set to unavailable. Non-functional.",
        group: "blank-error",
      },
      {
        id: 99,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://chlkqhfd.manus.space",
        dateDeployed: "Jul 8, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Set to unavailable. Non-functional.",
        group: "blank-error",
      },
      {
        id: 100,
        name: "Gymnastics Content Catalog - Universal CMS",
        url: "https://tirgoxto.manus.space",
        dateDeployed: "Jul 8, 2025",
        status: "Private",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Set to unavailable. Non-functional.",
        group: "blank-error",
      },
      {
        id: 101,
        name: "Gymnastics Content Mastery System",
        url: "https://hckjgffy.manus.space",
        dateDeployed: "Jun 21, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Blank page — no content visible despite having a title.",
        group: "blank-error",
      },
      {
        id: 102,
        name: "https://nbvzwngy.manus.space",
        url: "https://nbvzwngy.manus.space",
        dateDeployed: "Jun 5, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Completely blank. No content or functionality.",
        group: "blank-error",
      },
      {
        id: 103,
        name: "https://stfghtbn.manus.space",
        url: "https://stfghtbn.manus.space",
        dateDeployed: "Jun 27, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Blank or inaccessible site.",
        group: "blank-error",
      },
      {
        id: 104,
        name: "https://snkvyacw.manus.space (duplicate)",
        url: "https://snkvyacw.manus.space",
        dateDeployed: "Jul 1, 2025",
        status: "Public",
        polishLevel: "Blank/Error",
        recommendation: "Delete",
        purpose: "Duplicate entry already listed in Content Hub group.",
        group: "blank-error",
      },
    ],
  },
];

// Computed stats
export const allSites: Site[] = siteGroups.flatMap((g) => g.sites);

export const stats = {
  total: allSites.length,
  keep: allSites.filter((s) => s.recommendation === "Keep").length,
  delete: allSites.filter((s) => s.recommendation === "Delete").length,
  combine: allSites.filter((s) => s.recommendation === "Combine").length,
};
